// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBn7gC64iuuYbVZd_fFTUOU36fNN_84Zz0',
    appId: '1:125866533813:web:40ea55e4a64fa53a706ffc',
    messagingSenderId: '125866533813',
    projectId: 'bobjari-2f62c',
    authDomain: 'bobjari-2f62c.firebaseapp.com',
    storageBucket: 'bobjari-2f62c.appspot.com',
    measurementId: 'G-P2EJSS62X2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJgB8sb61zb9DGaN84k74Xiqw4D-3R1C0',
    appId: '1:125866533813:android:35b51e0fd1c1a444706ffc',
    messagingSenderId: '125866533813',
    projectId: 'bobjari-2f62c',
    storageBucket: 'bobjari-2f62c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDi35zhcY2vNvJwa3Cagfwo5s-Yk87D-A',
    appId: '1:125866533813:ios:ba845ba423dcb6da706ffc',
    messagingSenderId: '125866533813',
    projectId: 'bobjari-2f62c',
    storageBucket: 'bobjari-2f62c.appspot.com',
    iosClientId: '125866533813-bb1pbeb414mu1h5h5hik18iojp4foefn.apps.googleusercontent.com',
    iosBundleId: 'com.example.bobjariProj',
  );
}
